In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
import pandas as pd

df = pd.read_excel("../data/Customer_Churn_Dataset.xlsx")

# Convert TotalCharges to numeric
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

# Replace missing values
df["TotalCharges"] = df["TotalCharges"].fillna(0)

print("Dataset loaded successfully!")
print("Shape:", df.shape)
print("TotalCharges dtype:", df["TotalCharges"].dtype)

Dataset loaded successfully!
Shape: (7043, 23)
TotalCharges dtype: float64

In [3]:
df = pd.read_excel("../data/Customer_Churn_Dataset.xlsx")

print("Dataset loaded successfully!")
print("Shape:", df.shape)

display(df.head())

Dataset loaded successfully!
Shape: (7043, 23)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,numAdminTickets,numTechTickets,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0,0,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,One year,No,Mailed check,56.95,1889.5,0,0,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,0,0,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0,3,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,0,0,Yes

In [4]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nColumn names:")
print(df.columns.tolist())

Rows: 7043
Columns: 23

Column names:
['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'numAdminTickets', 'numTechTickets', 'Churn']

In [3]:
X = df.drop(columns=["customerID", "Churn"])
y = df["Churn"].map({"No": 0, "Yes": 1})

print("Features shape:", X.shape)
print("Target shape:", y.shape)

print("\nCategorical columns:")
print(X.select_dtypes(include=["object", "string", "category"]).columns.tolist())

print("\nNumerical columns:")
print(X.select_dtypes(include=["number"]).columns.tolist())

Features shape: (7043, 21)
Target shape: (7043,)

Categorical columns:
['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod']

Numerical columns:
['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges', 'numAdminTickets', 'numTechTickets']

##Encode Churn

In [6]:
y = y.map({
    "No": 0,
    "Yes": 1
})

print(y.value_counts())

Churn
0    5174
1    1869
Name: count, dtype: int64

##Separate categorical and numerical columns

In [7]:
categorical_cols = X.select_dtypes(
    include=["object", "string", "category"]
).columns.tolist()

numerical_cols = X.select_dtypes(
    include=["number"]
).columns.tolist()

print("Categorical columns:")
print(categorical_cols)

print("\nNumerical columns:")
print(numerical_cols)

Categorical columns:
['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'TotalCharges']

Numerical columns:
['SeniorCitizen', 'tenure', 'MonthlyCharges', 'numAdminTickets', 'numTechTickets']

##Encode categorical features

In [8]:
X_encoded = pd.get_dummies(
    X,
    columns=categorical_cols,
    drop_first=True,
    dtype=int
)

print("Shape after encoding:", X_encoded.shape)

display(X_encoded.head())

Shape after encoding: (7043, 6561)

,SeniorCitizen,tenure,MonthlyCharges,numAdminTickets,numTechTickets,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,...,TotalCharges_8496.7,TotalCharges_8529.5,TotalCharges_8543.25,TotalCharges_8547.15,TotalCharges_8564.75,TotalCharges_8594.4,TotalCharges_8670.1,TotalCharges_8672.45,TotalCharges_8684.8,TotalCharges_
0,0,1,29.85,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,0,34,56.95,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,0,2,53.85,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,0,45,42.30,0,3,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,0,2,70.70,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

##Scale numerical features

In [9]:
scaler = StandardScaler()

X_encoded[numerical_cols] = scaler.fit_transform(
    X_encoded[numerical_cols]
)

print("Numerical features scaled successfully!")
display(X_encoded.head())

Numerical features scaled successfully!

,SeniorCitizen,tenure,MonthlyCharges,numAdminTickets,numTechTickets,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,...,TotalCharges_8496.7,TotalCharges_8529.5,TotalCharges_8543.25,TotalCharges_8547.15,TotalCharges_8564.75,TotalCharges_8594.4,TotalCharges_8670.1,TotalCharges_8672.45,TotalCharges_8684.8,TotalCharges_
0,-0.439916,-1.277445,-1.160323,-0.404396,-0.335645,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,-0.439916,0.066327,-0.259629,-0.404396,-0.335645,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,-0.439916,-1.236724,-0.362660,-0.404396,-0.335645,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,-0.439916,0.514251,-0.746535,-0.404396,2.064301,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,-0.439916,-1.236724,0.197365,-0.404396,-0.335645,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

##final processed dataset

In [10]:
processed_df = X_encoded.copy()
processed_df["Churn"] = y.values

print("Final processed dataset shape:", processed_df.shape)

display(processed_df.head())

Final processed dataset shape: (7043, 6562)

,SeniorCitizen,tenure,MonthlyCharges,numAdminTickets,numTechTickets,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,...,TotalCharges_8529.5,TotalCharges_8543.25,TotalCharges_8547.15,TotalCharges_8564.75,TotalCharges_8594.4,TotalCharges_8670.1,TotalCharges_8672.45,TotalCharges_8684.8,TotalCharges_,Churn
0,-0.439916,-1.277445,-1.160323,-0.404396,-0.335645,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,-0.439916,0.066327,-0.259629,-0.404396,-0.335645,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,-0.439916,-1.236724,-0.362660,-0.404396,-0.335645,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
3,-0.439916,0.514251,-0.746535,-0.404396,2.064301,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,-0.439916,-1.236724,0.197365,-0.404396,-0.335645,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1

##Saving processed data

In [11]:
processed_df.to_csv(
    "../data/Telco_Churn_Processed.csv",
    index=False
)

print("Processed dataset saved successfully!")

Processed dataset saved successfully!

In [12]:
processed_check = pd.read_csv(
    "../data/Telco_Churn_Processed.csv"
)

print("Processed file loaded successfully!")
print("Shape:", processed_check.shape)

display(processed_check.head())

Processed file loaded successfully!
Shape: (7043, 6562)

,SeniorCitizen,tenure,MonthlyCharges,numAdminTickets,numTechTickets,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,...,TotalCharges_8529.5,TotalCharges_8543.25,TotalCharges_8547.15,TotalCharges_8564.75,TotalCharges_8594.4,TotalCharges_8670.1,TotalCharges_8672.45,TotalCharges_8684.8,TotalCharges_,Churn
0,-0.439916,-1.277445,-1.160323,-0.404396,-0.335645,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,-0.439916,0.066327,-0.259629,-0.404396,-0.335645,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,-0.439916,-1.236724,-0.362660,-0.404396,-0.335645,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
3,-0.439916,0.514251,-0.746535,-0.404396,2.064301,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,-0.439916,-1.236724,0.197365,-0.404396,-0.335645,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1

In [2]:
import pandas as pd

df = pd.read_excel("../data/Customer_Churn_Dataset.xlsx")

print("Dataset loaded successfully!")
print(df.shape)

Dataset loaded successfully!
(7043, 23)

In [4]:
import pandas as pd

df = pd.read_excel("../data/Customer_Churn_Dataset.xlsx")

# Convert TotalCharges from object to numeric
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

# Check missing values created during conversion
print("Missing TotalCharges:", df["TotalCharges"].isna().sum())

# Replace missing TotalCharges with 0
df["TotalCharges"] = df["TotalCharges"].fillna(0)

print("TotalCharges datatype:", df["TotalCharges"].dtype)

Missing TotalCharges: 11
TotalCharges datatype: float64

In [3]:
print(df["TotalCharges"].dtype)
print(df["TotalCharges"].head())

object
0      29.85
1     1889.5
2     108.15
3    1840.75
4     151.65
Name: TotalCharges, dtype: object

In [5]:
# Separate features and target
# Separate features and target

X = df.drop(columns=["customerID", "Churn"])
y = df["Churn"].map({"No": 0, "Yes": 1})

print("Features shape:", X.shape)
print("Target shape:", y.shape)

print("\nCategorical columns:")
print(X.select_dtypes(include=["object", "string", "category"]).columns.tolist())

print("\nNumerical columns:")
print(X.select_dtypes(include=["number"]).columns.tolist())

Features shape: (7043, 21)
Target shape: (7043,)

Categorical columns:
['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod']

Numerical columns:
['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges', 'numAdminTickets', 'numTechTickets']

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)
print("Training target shape:", y_train.shape)
print("Testing target shape:", y_test.shape)

Training data shape: (5634, 21)
Testing data shape: (1409, 21)
Training target shape: (5634,)
Testing target shape: (1409,)

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# Identify categorical and numerical columns
categorical_cols = X_train.select_dtypes(
    include=["object", "string", "category"]
).columns.tolist()

numerical_cols = X_train.select_dtypes(
    include=["number"]
).columns.tolist()

print("Categorical columns:", categorical_cols)
print("\nNumerical columns:", numerical_cols)

# Create preprocessing pipeline
preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numerical_cols),
        ("cat", OneHotEncoder(
            handle_unknown="ignore",
            drop="first",
            sparse_output=False
        ), categorical_cols)
    ],
    verbose_feature_names_out=False
)

# Make the output a pandas DataFrame
preprocessor.set_output(transform="pandas")

print("\nPreprocessor created successfully!")

Categorical columns: ['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod']

Numerical columns: ['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges', 'numAdminTickets', 'numTechTickets']

Preprocessor created successfully!

In [8]:
# Fit preprocessing only on training data
X_train_processed = preprocessor.fit_transform(X_train)

# Apply the same preprocessing to testing data
X_test_processed = preprocessor.transform(X_test)

print("Processed training data shape:", X_train_processed.shape)
print("Processed testing data shape:", X_test_processed.shape)

Processed training data shape: (5634, 32)
Processed testing data shape: (1409, 32)

In [9]:
import joblib

# Save processed datasets
X_train_processed.to_csv("../data/X_train_processed.csv", index=False)
X_test_processed.to_csv("../data/X_test_processed.csv", index=False)

# Save target datasets
y_train.to_csv("../data/y_train_processed.csv", index=False)
y_test.to_csv("../data/y_test_processed.csv", index=False)

# Save the fitted preprocessing pipeline
joblib.dump(preprocessor, "../data/preprocessor.pkl")

print("Processed datasets saved successfully!")
print("Preprocessor saved successfully!")

Processed datasets saved successfully!
Preprocessor saved successfully!